name: tests backend

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 12345678
          POSTGRES_DB: Predict_Emotion
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Checkout du code
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Installer Python
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Installer les dépendances Python
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Exécuter les tests
      - name: Run tests
        env:
          USER: postgres
          PASSWORD: 12345678
          HOST: localhost
          PORT: 5432
          DATABASE: Predict_Emotion
        run: |
          pytest -v
