name: tests backend

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev python3-dev build-essential
          sudo apt-get install -y postgresql postgresql-contrib
      
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start PostgreSQL and create database
        env:
          USER: postgres
          PASSWORD: 12345678
          HOST: localhost
          PORT: 5432
          DATABASE: Predict_Emotion
        run: |
          sudo systemctl start postgresql
        
          sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD '${PASSWORD}';"
          
          sudo -u postgres psql -c "CREATE DATABASE \"${DATABASE}\";"

      - name: Run tests
        env:
          USER: postgres
          PASSWORD: 12345678
          HOST: localhost
          PORT: 5432
          DATABASE: Predict_Emotion
        run: |
          pytest -v
