name: tests backend

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout du code
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Installer Python
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Installer PostgreSQL sur le runner
      - name: Install PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql postgresql-contrib
          sudo systemctl start postgresql
          sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD '12345678';"
          sudo -u postgres psql -c "CREATE DATABASE Predict_Emotion;"

      # Installer les dépendances Python
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Exécuter les tests
      - name: Run tests
        env:
          USER: postgres
          PASSWORD: 12345678
          HOST: localhost
          PORT: 5432
          DATABASE: Predict_Emotion
        run: |
          pytest -v
