name: tests backend

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name:  Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Install PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql postgresql-contrib

      - name: Start PostgreSQL and create data base
        env:
            USER: postgres
            PASSWORD: 12345678
            HOST: localhost
            PORT: 5432
            DATABASE: Predict_Emotion
        run: |
            # Start postgres service

            sudo systemctl start postgresql

            # set password for postgres user

            sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD '${PASSWORD}'"

            # Create the database

            sudo -u postgres psql -c "CREATE DATABASE "${DATABASE}""

      - name: Run tests
        env:
            USER: postgres
            PASSWORD: 12345678
            HOST: localhost
            PORT: 5432
            DATABASE: Predict_Emotion
        run: |
          pytest -v